// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dgyjaixkrvetxzsgzcrw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRneWphaXhrcnZldHh6c2d6Y3J3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg3Mzc5NTksImV4cCI6MjA2NDMxMzk1OX0.02x9PAclccJyde-I2L8ic_-KoqKVn67b98Dzs24l_ZU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);